apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod7
  name: pod7
  namespace: ashutoshh 
spec:
  volumes:   #  creating  volumes
   - name: ashuvol11
     emptyDir: {}
   - name: ashuvol2
     nfs:     #  creating  temperary directory 
      path: /data/ec2-user   #  data location on nfs server side 
      server: 172.31.81.173   # ip address of NFS  server 
  containers:
  - image: nginx
    name: pod77
    ports:
     - containerPort: 80  #  default port of portainer 
    volumeMounts:
     - name: ashuvol2   #  this volume must be present 
       mountPath:  /var/log/nginx/   # log location of nginx  server 
     - name: ashuvol11
       mountPath: /usr/share/nginx/html/   #  my web page will be dynamically growing 

  - image: alpine    # this will be my helper container 
    name: ashuc110
    volumeMounts:
     - name: ashuvol11
       mountPath: /mnt/data 
    command: ["/bin/sh","-c"," while  true; do date  >>/mnt/data/index.html; sleep 3; done"]

